# Generated by Django 4.1.7 on 2023-03-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_menagement_app', '0002_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
