# Generated by Django 4.1.7 on 2023-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_menagement_app', '0005_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
