# Generated by Django 4.1.7 on 2023-03-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_menagement_app', '0007_delete_user_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.IntegerField(),
        ),
    ]
